[mTSP]
num_agents = 4
num_tasks = 60
cost_multiplyer = 2
world_size = [10.0, 10.0]

[NetworkFlow]
num_columns = 40

[TestMilp]
num_trials = 3
max_tasks = 150
min_tasks = 100
max_agents = 4
min_agents = 4