[mTSP]
num_agents = 5
num_tasks = 40
cost_multiplyer = 2
world_size = [10.0, 10.0]

[NetworkFlow]
num_columns = 40

[TestMilp]
num_trials = 6
max_tasks = 60
min_tasks = 40
max_agents = 6
min_agents = 6