[mTSP]
num_agents = 5
num_tasks = 30
cost_multiplyer = 2
world_size = [10.0, 10.0]

[NetworkFlow]
num_columns = 40

[TestMilp]
num_trials = 6
max_tasks = 30
min_tasks = 10
max_agents = 5
min_agents = 5